name: Pull Request Stats

on:
    pull_request:
        types: [opened]

jobs:
    reuse:
        uses: Mason-Lin/reusable-workflows/.github/workflows/template-pr-stats.yml@master
        secrets: inherit
